import type { Event } from "./types"

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Introduction to Machine Learning",
    description: "Learn the fundamentals of ML algorithms and how they power modern AI applications.",
    club: "AI & Tech Club",
    category: "AI & Machine Learning",
    date: "Dec 15, 2024",
    time: "2:00 PM",
    location: "Room 101, Science Building",
    image: "/machine-learning-workshop.jpg",
    likes: 234,
    comments: 18,
    shares: 45,
  },
  {
    id: "2",
    title: "Quantum Physics Seminar",
    description: "Explore the mind-bending world of quantum mechanics with Dr. James Wilson.",
    club: "Physics Club",
    category: "Physics",
    date: "Dec 16, 2024",
    time: "3:30 PM",
    location: "Auditorium A",
    image: "/quantum-physics-abstract.png",
    likes: 156,
    comments: 12,
    shares: 28,
  },
  {
    id: "3",
    title: "Robotics Competition Prep",
    description: "Prepare for the annual robotics competition. All skill levels welcome!",
    club: "Robotics Club",
    category: "Robotics",
    date: "Dec 17, 2024",
    time: "5:00 PM",
    location: "Lab 3, Engineering Wing",
    image: "/robotics-competition.png",
    likes: 189,
    comments: 25,
    shares: 52,
  },
  {
    id: "4",
    title: "Organic Chemistry Lab Session",
    description: "Hands-on lab session exploring synthesis reactions and lab techniques.",
    club: "Chemistry Club",
    category: "Chemistry",
    date: "Dec 18, 2024",
    time: "1:00 PM",
    location: "Chemistry Lab, Building B",
    image: "/chemistry-laboratory.jpg",
    likes: 98,
    comments: 8,
    shares: 15,
  },
  {
    id: "5",
    title: "Biology Poster Presentation",
    description: "Student research presentations on genetics, ecology, and cell biology.",
    club: "Biology Club",
    category: "Biology",
    date: "Dec 19, 2024",
    time: "2:00 PM",
    location: "Student Center, Hall C",
    image: "/biology-research-presentation.jpg",
    likes: 142,
    comments: 14,
    shares: 32,
  },
  {
    id: "6",
    title: "Advanced Calculus Workshop",
    description: "Deep dive into calculus applications in engineering and physics.",
    club: "Mathematics Club",
    category: "Mathematics",
    date: "Dec 20, 2024",
    time: "4:00 PM",
    location: "Room 205, Math Building",
    image: "/mathematics-calculus.jpg",
    likes: 73,
    comments: 6,
    shares: 11,
  },
  {
    id: "7",
    title: "AI Ethics Discussion Panel",
    description: "Thoughtful discussion on ethical implications of artificial intelligence.",
    club: "AI & Tech Club",
    category: "AI & Machine Learning",
    date: "Dec 21, 2024",
    time: "3:00 PM",
    location: "Auditorium B",
    image: "/ai-ethics-discussion.png",
    likes: 267,
    comments: 31,
    shares: 68,
  },
  {
    id: "8",
    title: "Physics Hackathon 2024",
    description: "24-hour hackathon focused on solving real-world physics problems.",
    club: "Physics Club",
    category: "Physics",
    date: "Dec 22, 2024",
    time: "8:00 AM",
    location: "Innovation Center",
    image: "/physics-hackathon.jpg",
    likes: 312,
    comments: 42,
    shares: 85,
  },
  {
    id: "9",
    title: "Genetic Engineering Lecture",
    description: "Explore CRISPR technology and the future of gene editing.",
    club: "Biology Club",
    category: "Biology",
    date: "Dec 23, 2024",
    time: "2:30 PM",
    location: "Science Building Lecture Hall",
    image: "/genetic-engineering-crispr.jpg",
    likes: 201,
    comments: 19,
    shares: 44,
  },
  {
    id: "10",
    title: "Tech Startup Pitch Event",
    description: "Watch student entrepreneurs pitch their innovative tech ideas to investors.",
    club: "Technology Club",
    category: "Technology",
    date: "Dec 24, 2024",
    time: "6:00 PM",
    location: "Business School Auditorium",
    image: "/startup-pitch-event.png",
    likes: 445,
    comments: 56,
    shares: 123,
  },
  {
    id: "11",
    title: "Robotics Design Showcase",
    description: "See the latest robot designs and innovations from the Robotics Club.",
    club: "Robotics Club",
    category: "Robotics",
    date: "Dec 25, 2024",
    time: "1:00 PM",
    location: "Innovation Center Atrium",
    image: "/robot-design-showcase.jpg",
    likes: 276,
    comments: 33,
    shares: 71,
  },
  {
    id: "12",
    title: "Inorganic Chemistry Seminar",
    description: "Latest discoveries in catalysis and material science.",
    club: "Chemistry Club",
    category: "Chemistry",
    date: "Dec 26, 2024",
    time: "3:00 PM",
    location: "Chemistry Building Auditorium",
    image: "/inorganic-chemistry-materials.jpg",
    likes: 134,
    comments: 11,
    shares: 22,
  },
  {
    id: "13",
    title: "Linear Algebra Study Group",
    description: "Group study session for linear algebra concepts and problem-solving.",
    club: "Mathematics Club",
    category: "Mathematics",
    date: "Dec 27, 2024",
    time: "5:30 PM",
    location: "Library Study Room 4",
    image: "/linear-algebra-math.jpg",
    likes: 87,
    comments: 9,
    shares: 14,
  },
  {
    id: "14",
    title: "Astrophysics Stargazing Night",
    description: "Telescope observation night learning about distant galaxies and nebulae.",
    club: "Physics Club",
    category: "Physics",
    date: "Dec 28, 2024",
    time: "8:00 PM",
    location: "Observatory Rooftop",
    image: "/stargazing-astronomy-telescope.jpg",
    likes: 298,
    comments: 28,
    shares: 59,
  },
  {
    id: "15",
    title: "Biomedical Innovation Forum",
    description: "Discussion on cutting-edge biomedical technologies and research.",
    club: "Biology Club",
    category: "Biology",
    date: "Dec 29, 2024",
    time: "2:00 PM",
    location: "Health Sciences Building",
    image: "/biomedical-innovation-research.jpg",
    likes: 223,
    comments: 26,
    shares: 51,
  },
  {
    id: "16",
    title: "Deep Learning Workshop",
    description: "Hands-on workshop on neural networks and deep learning frameworks.",
    club: "AI & Tech Club",
    category: "AI & Machine Learning",
    date: "Dec 30, 2024",
    time: "10:00 AM",
    location: "Computer Lab 2",
    image: "/deep-learning-neural-networks.png",
    likes: 289,
    comments: 35,
    shares: 72,
  },
]
